server:
  port: 8083

spring:
  application:
    name: notification-service

brevo:
  api:
    url: ${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
    key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_SENDER_EMAIL:tranthanhtai1928@gmail.com}
    name: ${BREVO_SENDER_NAME:System Notification}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
