spring:
  application:
    name: common-framework
app:
  security:
    jwt:
      issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth}
      public-key: |
        ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyWt3dExzZKPa2GpoMIwU
        KA5Prybb6+sjd2mC0jwXFbTtzpbCAWwUFavGTcV8eqzUVwRoo63lAsP3p2tRhuLN
        JxrsOjaz27zQmljQDYcgjWV2eata+6Rwqj8mrBz7jy1zZmha+ealojI/oRA/1GSt
        /U/5fWWn2BBt7swL+FEh/U7CT5T6sH3aaeX2gtQt84j65pWHrHcuVjAtY0iXuXUJ
        GSk9wfCDmoslzEPGKwg3U3sFTulv5rHPZV91/ASH+D62LNcJypBlr8C2zmP5c0Bk
        snO32rqy9/SyOE3YcoJHhWZrjH5hN/54lRxIQZWn5R+roibEd30YL3sIAXf2T9oO
        ewIDAQAB
        -----END PUBLIC KEY-----}

  # ========================================================
  # Caching Configuration
  # ========================================================
  cache:
    type: ${CACHE_TYPE:redis} 
    redis:
      # Thời gian sống của cache (VD: 60m, 2h)
      time-to-live: ${CACHE_TTL_MINUTES:60m}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD:}
